spring:
  application:
    name: test-ahmed-rabbit-mq-client
#  rabbitmq:
#    #cache:
#      #channel:
#        #size: 10000
#    host: localhost
#    port: 5672
    #username: guest
    #password: guest
server:
  port: 8082